import Head from "next/head";
import Image from "next/image";
import { useDispatch, useSelector } from "react-redux";
import { increment, decrement, incrementByAmount } from "../redux/counter";

import Shoes from "./shoes";
import NavBar from "./navBar";
const Home = () => {
  const { count } = useSelector((state) => state.counter);
  const dispatch = useDispatch();

  return (
    <div className="container mx-auto min-w-full">
      <Head>
        <title>Løpesjappa 🏃</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="container mx-auto">
        <Shoes />

        <div className="App mt-10">
          <h1> The count is: {count}</h1>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(increment())}
          >
            increment
          </button>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(decrement())}
          >
            decrement
          </button>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(incrementByAmount(33))}
          >
            Increment by 33
          </button>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
