import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Shoes from "./shoes";
import NavBar from "./navBar";
const Home: NextPage = () => {
  return (
    <div className="container mx-auto min-w-full">
      <Head>
        <title>Løpesjappa 🏃</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="container mx-auto">
        <Shoes />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
