import Head from "next/head";

import { useDispatch, useSelector } from "react-redux";
import {
  increment,
  decrement,
  incrementByAmount,
  speak,
  lol,
} from "../redux/counter";
import Image from "next/image";
import { data } from "./data/data";

import Shoes from "./shoes";
import Hero from "./hero";
import News from "./news";
const Home = () => {
  const { count } = useSelector((state) => state.counter);
  const dispatch = useDispatch();

  //console.log("Hei loggen: ", data);

  // Logic for handeling data from mock database.
  //
  let shoes = [];
  data[0].shoes.forEach((e) => {
    //console.log(e);
    shoes.push(e);
  });

  console.log("log fra object", Object.entries(data));
  let clothes = [];
  data[1].clothes.forEach((e) => clothes.push(e));
  console.log("Hei fra shoes array: ", shoes);
  // console.log("Hei fra clothes array: ", clothes);

  //Logging product names
  console.log(clothes.forEach((e) => console.log(e.product)));

  const shoe = function (arr) {
    arr.forEach((e) => <li key={e.id}>{e.product}</li>);
  };
  return (
    <div className="container mx-auto min-w-full">
      <Head>
        <title>Løpesjappa 🏃</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className="container mx-auto text-center">
        <div className="App text-gray-100">
          <h1> The count is: {count}</h1>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(increment())}
          >
            increment
          </button>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(decrement())}
          >
            decrement
          </button>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(incrementByAmount(33))}
          >
            Increment by 33
          </button>
          <button
            className="m-2 p-2 bg-gray-400"
            onClick={() => dispatch(lol())}
          >
            Speak to console
          </button>
        </div>

        <ul>
          {shoes.map((e) => {
            return (
              <li key={e.id}>
                <div>{e.product}</div>
                <img src={e.img} alt="Image for Nike running shoes" />
              </li>
            );
          })}
          <p>Hei fra UL</p>
        </ul>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
